# version: "3.8"
# services:
#   dynamodb:
#     image: amazon/dynamodb-local
#     ports:
#       - "8001:8000"
#     command: "-jar DynamoDBLocal.jar -inMemory"

#   minio:
#     image: minio/minio
#     container_name: minio
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     environment:
#       - MINIO_ROOT_USER=localuser
#       - MINIO_ROOT_PASSWORD=locallocal
#     command: server /data --console-address ":9001"
